version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dockerAdmin
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
